config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:sessions, :passwords]
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "users", skip: [:sessions], controllers: { registrations: "registrations", confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'blogs#index'

  resources :blogs, only: [:index, :show]
  get "author", to: "authors#index"
  post "blogusers/create"
  resources :comments, only: [:create]
  #get "talk", to: "talks#show"
  root "talks#index"

  authenticated do
    devise_scope :admin do
      namespace :admin do
        resources :blogs, only: [:index, :new ,:create, :edit, :update, :destroy, :search]
        root "blogs#default_admin_page"
        patch 'blogs/:id/confirm', to: 'blogs#confirm'
        resources :blogs do
          collection do
            get 'blogs/search', to: 'blogs#search'
            patch :confirm
            post :confirm
          end
          resources :comments, controller: "blogs/comments", only: [:index, :destroy]
        end
        #root to: "sessions#new", as: :unauthenticated
        root 'admin#blogs#index'
        resources :users, only: [:index, :list]
        get "users/list", to: "users#list"

      end
    end
  end

  devise_scope :admin do
    get "admin", to: "admin/sessions#new", as: :admin_session
    post "admin", to:  "admin/sessions#create", as: :admin_create
    delete "admin/sign_out", to: "admin/sessions#destroy", as: :admin_destroy
  end

  devise_scope :user do
    get "users/sign_in", to: "devise/sessions#new", as: :user_session
    post "users/sign_in", to: "devise/sessions#create", as: :user_create
    delete "users/sign_out", to: "devise/sessions#destroy", as: :user_destroy
    get "users/:id/edit", to: "devise/registrations#edit", as: :user_edit

    resources :users, only: [:show]
  end

end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :blog_users

  mount_uploader :image, ImageUploader
  mount_uploader :authorImage, AuthorImageUploader

  validates :title, presence: {message: :title_empty},
            length: {maximum: 255, message: :title_length}

  validates :datePublic, presence: {message: :datePublic_empty}

  validates :image, presence: {message: :image_empty}
  validates_size_of :image, maximum: 2.megabytes, message: :image_size  

  validates :content, presence: {message: :content_empty}
  validates_size_of :content, maximum: 2.megabytes, message: :content_length

  validates :author, presence: {message: :author_empty },
            length: {maximum: 32, message: :author_length}

  validates :jobName, presence: {message: :jobName_empty },
            length: {maximum: 32, message: :jobName_length}

  validates :age, numericality: {message: :age_number}, presence: {message: :age_empty},
            length: { maximum: 2, message: :age_length }
  
  validates_size_of :authorImage, maximum: 2.megabytes, message: :authorImage_size  
  validate :file_format

  def file_format
    unless valid_extension? self.image.filename
      errors.add(:image, I18n.t("errors.extenstion"))
    end
    unless valid_extension? self.authorImage.filename
      errors.add(:authorImage, I18n.t("errors.extenstion"))
    end
  end

  def valid_extension? filename
    return true if filename.nil?
    ext = File.extname(filename)
    %w(.jpeg .png .jpg).include? ext.downcase
  end

  scope :blog_all, -> {
    where(isPublic: 1)
    .get_data
    .recent
  }

  scope :blog_public, -> {
    where(isSuggest: 1, isPublic: 1)
      .get_data
      .recent
  }

  scope :blog_list1, -> {
    where(category_id: 1 , isPublic: 1)
      .get_data
      .recent
  }

  scope :blog_list2, -> {
    where(category_id: 2 , isPublic: 1)
      .get_data
      .recent
  }

  scope :blog_list3, -> {
    where(category_id: 3 , isPublic: 1)
      .get_data
      .recent
  }

  scope :get_data, ->{select(:id, :title, :image, :category_id, :isSuggest, :datePublic)}
  scope :recent, ->{order('datePublic DESC')}

end

app/controllers/admin/blogs/comments_controller.rb
class Admin::Blogs::CommentsController < ApplicationController
  before_action :find_blog, only: [:index, :destroy]
  layout 'admin'

  def index
    @comments = @blog.comments.includes(:user).reverse
  end

  # def destroy
  #   @comment = @blog.comments.find_by(id: params[:id]).destroy
  #   @comments = @blog.comments
  #   respond_to do |format|
  #     format.js
  #   end
  # end

  private
  def find_blog
    @blog = Blog.find_by id: params[:blog_id]
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :search]
  layout 'admin'

  DEFAULT_IMAGE_URL = "/assets/avatar_default.png"

  # GET /blogs
  # GET /json
  def index
    @search = Blog.includes(:category).search(params[:q])
    if params[:sort_by] == "ASC"
      @search.sorts = ['created_at ASC'] if @search.sorts.empty?
    elsif params[:sort_by] == "DESC"
      @search.sorts = ['created_at DESC'] if @search.sorts.empty?
    end

    @blogs = @search.result.paginate(page: params[:page],
                                     per_page: 20)
    respond_to do |format|
      format.html
      format.json { render json: { lists: @blogs } }
    end
  end

  def show
  end

  # GET /blogs/new
  def new
  	@blog = Blog.new
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    if params[:blog][:image].present?
      @blog.image = File.open(Rails.root.to_s + "/public" + params[:blog][:image])
    end
    
    if params[:blog][:authorImage].blank?
      @blog.authorImage = File.open(Rails.root.to_s + "/app/assets/images/avatar_default.png")
    else
      @blog.authorImage = File.open(Rails.root.to_s + "/public" + params[:blog][:authorImage])
    end

    render :new and return if params[:re_new].present?

    respond_to do |format|
      if @blog.save
        format.html { redirect_to admin_blogs_path }
        flash[:success] =  t "alert.blog.create"
        format.json { render :index, status::created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update  
    @blog.assign_attributes blog_params

    if params[:blog][:image].present?
      @blog.image = File.open(Rails.root.to_s + "/public/" + params[:blog][:image])   

      if params[:blog][:authorImage] == DEFAULT_IMAGE_URL
        @blog.authorImage = File.open(Rails.root.to_s + "/app/assets/images/avatar_default.png")
      else
        @blog.authorImage = File.open(Rails.root.to_s + "/public/" + params[:blog][:authorImage])
      end    
    end        

    render :edit and return if params[:re_edit].present?

    respond_to do |format|
      if @blog.save
        unless params[:redirect_check]
          format.html { redirect_to admin_blogs_path }
          flash[:success] = t "alert.blog.update"
          format.json { render :index, status: :ok, location: @blog }
        else
          format.json
        end  
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to admin_blogs_url }
      flash[:success] = t "alert.blog.delete"
      format.json { head :no_content }
    end
  end

  def confirm
    if params[:id]
      @blog = Blog.find(params[:id])
      @blog.assign_attributes blog_params
      render :edit if @blog.invalid?
    else
      @blog = Blog.new(blog_params)
      render :new if @blog.invalid?
    end
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :category_id, :isSuggest, :image, :image_cache, :isPublic, :datePublic,
                                   :content, :author, :jobName, :age, :authorImage, :authorImage_cache)
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :get_blog, only: [:show]

  def index
    @count_action_interest = BlogUser.action_interest
    @count_action_like = BlogUser.action_like
    @count_action_dislike = BlogUser.action_dislike
    @count_action_disappoint = BlogUser.action_disappoint

    @blogs = Blog.includes(:category).blog_all
                 .paginate(page: params[:page], per_page: 20)
    @blogs_public = Blog.includes(:category).blog_public
                 .paginate(page: params[:page], per_page: 10)
    @blogs1 = Blog.includes(:category).blog_list1
                 .paginate(page: params[:page], per_page: 10)
    @blogs2= Blog.includes(:category).blog_list2
                .paginate(page: params[:page], per_page: 10)
    @blogs3 = Blog.includes(:category).blog_list3
                 .paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @blog = Blog.find(params[:id])

    if current_user
      @action = BlogUser.where(user_id: current_user.id,
                               blog_id: @blog.id).first

      @check_action = @action.action if @action
    else
      @check_action = cookies[:action_status_check]
    end

    @count_action = BlogUser.where(blog_id: @blog.id)
                        .select(:action)
                        .group(:action).count

    @blog_comments = @blog.comments.includes(:user).order('created_at ASC')

  end

  private

  def get_blog
    @blog = Blog.find(params[:id])
    unless @blog
      redirect_to root_url
    end
  end

end

app/helpers/blog_helper.rb
module BlogHelper
  def custom_errors(blog)
    @title_error = ''
    @category_error = ''
    @datePublic_error = ''
    @image_error = ''
    @content_error = ''
    @author_error = ''
    @jobName_error = ''
    @age_error = ''
    @authorImage_error = ''
    if blog.errors.any?
      blog.errors.messages.each_with_index do |msg,idx|
        if msg[0].eql?(:title)
          @title_error = msg[1].last
        end
        if msg[0].eql?(:category)
          @category_error = msg[1].last
        end
        if msg[0].eql?(:datePublic)
          @datePublic_error = msg[1].last
        end
        if msg[0].eql?(:image)
          @image_error = msg[1].last
        end
        if msg[0].eql?(:content)
          @content_error = msg[1].last
        end
        if msg[0].eql?(:author)
          @author_error = msg[1].last
        end
        if msg[0].eql?(:jobName)
          @jobName_error = msg[1].last
        end
        if msg[0].eql?(:age)
          @age_error = msg[1].last
        end
        if msg[0].eql?(:authorImage)
          @authorImage_error = msg[1].last
        end
      end
    end
  end

end

app/views/blogs/_blog_cate1_list.html.erb
<% @blogs1.each do |blog| %>
    <li>
      <a href="<%= blog_path(blog.id) %>" style="text-decoration : none" >
        <div class="row">
          <% if blog.isSuggest == 1 %>
              <div class="suggest">
                <img src="/assets/suggest.png" alt="">
              </div>
          <% end %>
          <div class="blog">
            <div class="image_thum">
              <img src=<%= blog.image.url %> alt="">
            </div>
            <div class="title-blog">
              <p><%= blog.title %></p>
            </div>
            <div class="row">
              <div class="col-xs-6">
                <% case blog.category_id %>
                <% when 1 %>
                    <div class="category" style="border: 1px solid #89c529;">
                      <p style="color: #89c529;"><%= blog.category.name %></p>
                    </div>
                <% when 2 %>
                    <div class="category" style="border: 1px solid #f8879f;">
                      <p style="color: #f8879f;"><%= blog.category.name %></p>
                    </div>
                <% when 3 %>
                    <div class="category" style="border: 1px solid #41b1e5;">
                      <p style="color: #41b1e5;"><%= blog.category.name %></p>
                    </div>
                <% end %>
                <div class="public-time">
                  <p><%= blog.datePublic.to_date.strftime("%Y.%m.%d") %></p>
                </div>
              </div>
              <div class="col-xs-6">
                <div class="col-xs-3 action">
                  <span><img src="/assets/interesting.png" alt=""></span>

                  <% @count_action_interest.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_interest.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/like.png" alt=""></span>

                  <% @count_action_like.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_like.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/dislike.png" alt=""></span>

                  <% @count_action_dislike.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_dislike.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/disappoint.png" alt=""></span>

                  <% @count_action_disappoint.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_disappoint.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
          <hr>
        </div>
      </a>
    </li>
<% end %>

app/views/blogs/_blog_cate2_list.html.erb
<% @blogs2.each do |blog| %>
    <li>
      <a href="<%= blog_path(blog.id) %>" style="text-decoration : none" >
        <div class="row">
          <% if blog.isSuggest == 1 %>
              <div class="suggest">
                <img src="/assets/suggest.png" alt="">
              </div>
          <% end %>
          <div class="blog">
            <div class="image_thum">
              <img src=<%= blog.image.url %> alt="">
            </div>
            <div class="title-blog">
              <p><%= blog.title %></p>
            </div>
            <div class="row">
              <div class="col-xs-6">
                <% case blog.category_id %>
                <% when 1 %>
                    <div class="category" style="border: 1px solid #89c529;">
                      <p style="color: #89c529;"><%= blog.category.name %></p>
                    </div>
                <% when 2 %>
                    <div class="category" style="border: 1px solid #f8879f;">
                      <p style="color: #f8879f;"><%= blog.category.name %></p>
                    </div>
                <% when 3 %>
                    <div class="category" style="border: 1px solid #41b1e5;">
                      <p style="color: #41b1e5;"><%= blog.category.name %></p>
                    </div>
                <% end %>
                <div class="public-time">
                  <p><%= blog.datePublic.to_date.strftime("%Y.%m.%d") %></p>
                </div>
              </div>
              <div class="col-xs-6">
                <div class="col-xs-3 action">
                  <span><img src="/assets/interesting.png" alt=""></span>

                  <% @count_action_interest.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_interest.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/like.png" alt=""></span>

                  <% @count_action_like.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_like.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/dislike.png" alt=""></span>

                  <% @count_action_dislike.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_dislike.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/disappoint.png" alt=""></span>

                  <% @count_action_disappoint.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_disappoint.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
          <hr>
        </div>
      </a>
    </li>
<% end %>

app/views/blogs/_blog_cate3_list.html.erb
<% @blogs3.each do |blog| %>
    <li>
      <a href="<%= blog_path(blog.id) %>" style="text-decoration : none" >
        <div class="row">
          <% if blog.isSuggest == 1 %>
              <div class="suggest">
                <img src="/assets/suggest.png" alt="">
              </div>
          <% end %>
          <div class="blog">
            <div class="image_thum">
              <img src=<%= blog.image.url %> alt="">
            </div>
            <div class="title-blog">
              <p><%= blog.title %></p>
            </div>
            <div class="row">
              <div class="col-xs-6">
                <% case blog.category_id %>
                <% when 1 %>
                    <div class="category" style="border: 1px solid #89c529;">
                      <p style="color: #89c529;"><%= blog.category.name %></p>
                    </div>
                <% when 2 %>
                    <div class="category" style="border: 1px solid #f8879f;">
                      <p style="color: #f8879f;"><%= blog.category.name %></p>
                    </div>
                <% when 3 %>
                    <div class="category" style="border: 1px solid #41b1e5;">
                      <p style="color: #41b1e5;"><%= blog.category.name %></p>
                    </div>
                <% end %>
                <div class="public-time">
                  <p><%= blog.datePublic.to_date.strftime("%Y.%m.%d") %></p>
                </div>
              </div>
              <div class="col-xs-6">
                <div class="col-xs-3 action">
                  <span><img src="/assets/interesting.png" alt=""></span>

                  <% @count_action_interest.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_interest.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/like.png" alt=""></span>

                  <% @count_action_like.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_like.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/dislike.png" alt=""></span>

                  <% @count_action_dislike.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_dislike.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/disappoint.png" alt=""></span>

                  <% @count_action_disappoint.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_disappoint.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
          <hr>
        </div>
      </a>
    </li>
<% end %>

app/views/blogs/_blog_detail.html.erb
<% @blogs.each do |blog| %>
  <li>
    <a href=<%= blog_path(blog.id) %>>
      <div class="row">
        <% if blog.isSuggest == 1 %>
          <div class="suggest">
            <img src="/assets/suggest.png" alt="">
          </div>
        <% end %>
        <div class="blog">
          <div class="title-blog">
            <p><%= blog.title %></p>
          </div>
          <div class="row">
            <div class="col-xs-6">
              <div class="category">
                <p><%= blog.category.name %></p>
              </div>
              <div class="public-time">
                <p><%= blog.datePublic.to_date.strftime("%Y.%m.%d") %></p>
              </div>
            </div>
            <div class="col-xs-6">
              <div class="col-xs-3 action">
                <img src="/assets/interesting.png" alt="">
                <span><p><%= blog.interest %></p></span>
              </div>
              <div class="col-xs-3 action">
                <span><img src="/assets/like.png" alt=""></span>
                <span><p><%= blog.like %></p></span>
              </div>
              <div class="col-xs-3 action">
                <span><img src="/assets/dislike.png" alt=""></span>
                <span><p><%= blog.dislike %></p></span>
              </div>
              <div class="col-xs-3 action">
                <span><img src="/assets/disappoint.png" alt=""></span>
                <span><p><%= blog.disappoint %></p></span>
              </div>
            </div>
          </div>
        </div>
        <hr>
      </div>
    </a>
  </li>
<% end %>

app/views/blogs/_blog_list.html.erb
<% @blogs.each do |blog| %>
  <li>
    <a href="<%= blog_path(blog.id) %>" style="text-decoration : none" >
      <div class="row">
        <% if blog.isSuggest == 1 %>
          <div class="suggest">
            <img src="/assets/suggest.png" alt="">
          </div>
        <% end %>
        <div class="blog">
          <div class="image_thum">
            <img src=<%= blog.image.url %> alt="">
          </div>
          <div class="title-blog">
            <p><%= blog.title %></p>
          </div>
          <div class="row">
            <div class="col-xs-6">
              <% case blog.category_id %>
              <% when 1 %>
                <div class="category" style="border: 1px solid #89c529;">
                  <p style="color: #89c529;"><%= blog.category.name %></p>
                </div>
              <% when 2 %>
                <div class="category" style="border: 1px solid #f8879f;">
                  <p style="color: #f8879f;"><%= blog.category.name %></p>
                </div>
              <% when 3 %>
                <div class="category" style="border: 1px solid #41b1e5;">
                  <p style="color: #41b1e5;"><%= blog.category.name %></p>
                </div>
              <% end %>
              <div class="public-time">
                <p><%= blog.datePublic.to_date.strftime("%Y.%m.%d") %></p>
              </div>
            </div>
            <div class="col-xs-6">
                <div class="col-xs-3 action">
                  <span><img src="/assets/interesting.png" alt=""></span>

                  <% @count_action_interest.each do |key,value| %>
                    <% if key == blog.id %>
                      <span><p><%= value %></p></span>
                    <% end %>
                  <% end %>
                  <% unless @count_action_interest.key? blog.id %>
                    <span><p>0</p></span>
                  <% end %>

                </div>
              <div class="col-xs-3 action">
                <span><img src="/assets/like.png" alt=""></span>

                <% @count_action_like.each do |key,value| %>
                  <% if key == blog.id %>
                    <span><p><%= value %></p></span>
                  <% end %>
                <% end %>
                <% unless @count_action_like.key? blog.id %>
                    <span><p>0</p></span>
                <% end %>

              </div>
              <div class="col-xs-3 action">
                <span><img src="/assets/dislike.png" alt=""></span>

                <% @count_action_dislike.each do |key,value| %>
                  <% if key == blog.id %>
                    <span><p><%= value %></p></span>
                  <% end %>
                <% end %>
                <% unless @count_action_dislike.key? blog.id %>
                    <span><p>0</p></span>
                <% end %>

              </div>
              <div class="col-xs-3 action">
                <span><img src="/assets/disappoint.png" alt=""></span>

                <% @count_action_disappoint.each do |key,value| %>
                  <% if key == blog.id %>
                    <span><p><%= value %></p></span>
                  <% end %>
                <% end %>
                <% unless @count_action_disappoint.key? blog.id %>
                    <span><p>0</p></span>
                <% end %>

              </div>
            </div>
          </div>
        </div>
        <hr>
      </div>
    </a>
  </li>
<% end %>

app/views/blogs/_blog_public_list.html.erb
<% @blogs_public.each do |blog| %>
    <li>
      <a href="<%= blog_path(blog.id) %>" style="text-decoration : none" >
        <div class="row">
          <% if blog.isSuggest == 1 %>
              <div class="suggest">
                <img src="/assets/suggest.png" alt="">
              </div>
          <% end %>
          <div class="blog">
            <div class="image_thum">
              <img src=<%= blog.image.url %> alt="">
            </div>
            <div class="title-blog">
              <p><%= blog.title %></p>
            </div>
            <div class="row">
              <div class="col-xs-6">
                <% case blog.category_id %>
                <% when 1 %>
                    <div class="category" style="border: 1px solid #89c529;">
                      <p style="color: #89c529;"><%= blog.category.name %></p>
                    </div>
                <% when 2 %>
                    <div class="category" style="border: 1px solid #f8879f;">
                      <p style="color: #f8879f;"><%= blog.category.name %></p>
                    </div>
                <% when 3 %>
                    <div class="category" style="border: 1px solid #41b1e5;">
                      <p style="color: #41b1e5;"><%= blog.category.name %></p>
                    </div>
                <% end %>
                <div class="public-time">
                  <p><%= blog.datePublic.to_date.strftime("%Y.%m.%d") %></p>
                </div>
              </div>
              <div class="col-xs-6">
                <div class="col-xs-3 action">
                  <span><img src="/assets/interesting.png" alt=""></span>

                  <% @count_action_interest.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_interest.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/like.png" alt=""></span>

                  <% @count_action_like.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_like.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/dislike.png" alt=""></span>

                  <% @count_action_dislike.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_dislike.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
                <div class="col-xs-3 action">
                  <span><img src="/assets/disappoint.png" alt=""></span>

                  <% @count_action_disappoint.each do |key,value| %>
                      <% if key == blog.id %>
                          <span><p><%= value %></p></span>
                      <% end %>
                  <% end %>
                  <% unless @count_action_disappoint.key? blog.id %>
                      <span><p>0</p></span>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
          <hr>
        </div>
      </a>
    </li>
<% end %>

app/views/blogs/index.js.erb
$('.my-blogs-user').append('<%= j render 'blog_list' %>');
$('a.infinite-scrolling-user').attr('href', "<%= blogs_path page: @blogs.next_page %>");

<% unless @blogs.next_page %>
  $('a.infinite-scrolling-user').remove();
<% end %>