config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:sessions, :passwords]
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "users", skip: [:sessions], controllers: { registrations: "registrations", confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'blogs#index'

  resources :blogs, only: [:index, :show]
  get "author", to: "authors#index"
  post "blogusers/create"
  resources :comments, only: [:create]
  #get "talk", to: "talks#show"
  root "talks#index"

  authenticated do
    devise_scope :admin do
      namespace :admin do
        resources :blogs, only: [:index, :new ,:create, :edit, :update, :destroy, :search]
        root "blogs#default_admin_page"
        patch 'blogs/:id/confirm', to: 'blogs#confirm'
        resources :blogs do
          collection do
            get 'blogs/search', to: 'blogs#search'
            patch :confirm
            post :confirm
          end
          resources :comments, controller: "blogs/comments", only: [:index, :destroy]
        end
        #root to: "sessions#new", as: :unauthenticated
        root 'admin#blogs#index'
        resources :users, only: [:index, :list]
        get "users/list", to: "users#list"

      end
    end
  end

  devise_scope :admin do
    get "admin", to: "admin/sessions#new", as: :admin_session
    post "admin", to:  "admin/sessions#create", as: :admin_create
    delete "admin/sign_out", to: "admin/sessions#destroy", as: :admin_destroy
  end

  devise_scope :user do
    get "users/sign_in", to: "devise/sessions#new", as: :user_session
    post "users/sign_in", to: "devise/sessions#create", as: :user_create
    delete "users/sign_out", to: "devise/sessions#destroy", as: :user_destroy
    get "users/:id/edit", to: "devise/registrations#edit", as: :user_edit

    resources :users, only: [:show]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, ImageUploader

  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, dependent: :destroy
  has_many :blog_users

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'

  def list
    unless params[:rate_action].to_i == 0
      @actions = BlogUser.where(action: params[:rate_action].to_i).group(:user_id).count
      @users = User.select(:id, :email, :name, :avatar)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
  end

end

app/views/users/show.html.erb
<div class="profile">
  <div class="row" id="first_layout" >
    <div class="avatar_layout_user">
      <% if @user.avatar? %>
        <img src="<%= @user.avatar %>" alt="">
      <% else %>
        <img src="/assets/avatar_default">
      <% end %>
    </div>
    <div class="author_info">
      <p class="author_title"><%= t"profile.author_title" %></p>
      <p class="author_name">
        <span class="name"><%= @user.name %></span>
        <span class="job"><%= t"profile.author_job" %></span>
      </p>
      <div class="author_birth_place">
        <div class="label">
          <p><%= t"profile.author_birth_place" %></p>
        </div>
        <div class="explain">
          <p><%= t"profile.author_birth_place_text" %></p>
        </div>
      </div>
      <div class="author_age">
        <div class="label">
          <p><%= t"profile.author_age" %></p>
        </div>
        <div class="explain">
          <p><%= t"profile.author_age_text" %></p>
        </div>
      </div>
      <div class="author_subject">
        <div class="label">
          <p><%= t"profile.author_subject" %></p>
        </div>
        <div class="explain">
          <p><%= t"profile.author_subject_text" %></p>
        </div>
      </div>
    </div>
    <div class="author_intro_text">
      <p><%= t"profile.author_intro_text" %></p>
    </div>

  </div>

  <div style="padding-left: 10%;">
    <div class="row" id="second_layout">
      <div class="label">
        <a href="<%= user_edit_path(current_user) %>">プロファイル編集</a>
      </div>
      <div class="label" id="logout">
        <%= link_to "ログアウト", user_destroy_path, :method => :delete %>
      </div>
    </div>
  </div>

  <!--<div class="row" id="second_layout" >-->
  <!--<div class="title">-->
  <!--<p><%= t"profile.second_layout_title" %></p>-->
  <!--</div>-->
  <!--<div class="body">-->
  <!--&lt;!&ndash;<img src="/assets/thum_image.png" alt="">&ndash;&gt;-->
  <!--<p><%= t"profile.second_layout_body" %></p>-->
  <!--</div>-->
  <!--</div>-->
  <!--<div class="row" id="third_layout" >-->
  <!--<div class="title">-->
  <!--<p><%= t"profile.third_layout_title" %></p>-->
  <!--</div>-->
  <!--<div class="body">-->
  <!--<p><%= t"profile.third_layout_body" %></p>-->
  <!--</div>-->
  <!--</div>-->
</div>

<script>
  $("#logout").on("click", function () {
    sessionStorage.clear();
  });
</script>