config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:sessions, :passwords]
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "users", skip: [:sessions], controllers: { registrations: "registrations", confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'blogs#index'

  resources :blogs, only: [:index, :show]
  get "author", to: "authors#index"
  post "blogusers/create"
  resources :comments, only: [:create]
  #get "talk", to: "talks#show"
  root "talks#index"

  authenticated do
    devise_scope :admin do
      namespace :admin do
        resources :blogs, only: [:index, :new ,:create, :edit, :update, :destroy, :search]
        root "blogs#default_admin_page"
        patch 'blogs/:id/confirm', to: 'blogs#confirm'
        resources :blogs do
          collection do
            get 'blogs/search', to: 'blogs#search'
            patch :confirm
            post :confirm
          end
          resources :comments, controller: "blogs/comments", only: [:index, :destroy]
        end
        #root to: "sessions#new", as: :unauthenticated
        root 'admin#blogs#index'
        resources :users, only: [:index, :list]
        get "users/list", to: "users#list"

      end
    end
  end

  devise_scope :admin do
    get "admin", to: "admin/sessions#new", as: :admin_session
    post "admin", to:  "admin/sessions#create", as: :admin_create
    delete "admin/sign_out", to: "admin/sessions#destroy", as: :admin_destroy
  end

  devise_scope :user do
    get "users/sign_in", to: "devise/sessions#new", as: :user_session
    post "users/sign_in", to: "devise/sessions#create", as: :user_create
    delete "users/sign_out", to: "devise/sessions#destroy", as: :user_destroy
    get "users/:id/edit", to: "devise/registrations#edit", as: :user_edit

    resources :users, only: [:show]
  end

end

app/views/shared/_footer.html.erb
<footer>
  <div class="row" >
    <a href="/">
      <div class="col-xs-4 footer-menu <%= params[:controller] == "talks" ? "active" : "" %>">
        <div class="comment">
          <img class="default" src="/assets/talk.png" alt="">
          <img class="selected" src="/assets/talk-click.png" alt="">
          <span><p>トーク</p></span>
        </div>
      </div>
    </a>

    <div id="show-popup">
      <div class="col-xs-4 footer-menu <%= params[:controller] == "blogs" ? "active" : "" %>">
        <div class="detail">
          <img class="default" src="/assets/top.png" alt="">
          <img class="selected" src="/assets/top-click.png" alt="">
          <span><p>ブログ</p></span>
        </div>
      </div>
    </div>

    <a href="<%= user_path(current_user.id) %>">
      <div class="col-xs-4 footer-menu <%= params[:controller] == "users" ? "active" : "" %>">
        <div class="author">
          <img class="default" src="/assets/profile.png" alt="">
          <img class="selected" src="/assets/profile-click.png" alt="">
          <span><p>プロフィール</p></span>
        </div>
      </div>
    </a>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-top">
    <% if params[:controller] == "authors" %>
      <div class="notice">
        <a href="<%= blogs_path %>">
          <img src="/assets/profile-icon-back.png" alt="">
        </a>
      </div>
      <div class="title-text-profile">
        <p><%= t"header.profile-text" %></p>
      </div>
    <% else %>
      <% if params[:controller] == "blogs" && params[:action] == "show" %>
        <div class="notice">
          <a href="<%= blogs_path %>">
            <img src="/assets/profile-icon-back.png" alt="">
          </a>
        </div>
      <% else %>
        <div class="notice">
          <img src="/assets/noti.png" alt="">
        </div>
      <% end %>

      <% if params[:controller] == "talks" %>
        <div class="title-text">
          <p><%= "トーク" %></p>
        </div>
      <% else %>
        <div class="title-text">
          <p><%= t"header.text" %></p>
        </div>
      <% end %>

    <% end %>
  </div>
</header>