config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:sessions, :passwords]
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "users", skip: [:sessions], controllers: { registrations: "registrations", confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'blogs#index'

  resources :blogs, only: [:index, :show]
  get "author", to: "authors#index"
  post "blogusers/create"
  resources :comments, only: [:create]
  #get "talk", to: "talks#show"
  root "talks#index"

  authenticated do
    devise_scope :admin do
      namespace :admin do
        resources :blogs, only: [:index, :new ,:create, :edit, :update, :destroy, :search]
        root "blogs#default_admin_page"
        patch 'blogs/:id/confirm', to: 'blogs#confirm'
        resources :blogs do
          collection do
            get 'blogs/search', to: 'blogs#search'
            patch :confirm
            post :confirm
          end
          resources :comments, controller: "blogs/comments", only: [:index, :destroy]
        end
        #root to: "sessions#new", as: :unauthenticated
        root 'admin#blogs#index'
        resources :users, only: [:index, :list]
        get "users/list", to: "users#list"

      end
    end
  end

  devise_scope :admin do
    get "admin", to: "admin/sessions#new", as: :admin_session
    post "admin", to:  "admin/sessions#create", as: :admin_create
    delete "admin/sign_out", to: "admin/sessions#destroy", as: :admin_destroy
  end

  devise_scope :user do
    get "users/sign_in", to: "devise/sessions#new", as: :user_session
    post "users/sign_in", to: "devise/sessions#create", as: :user_create
    delete "users/sign_out", to: "devise/sessions#destroy", as: :user_destroy
    get "users/:id/edit", to: "devise/registrations#edit", as: :user_edit

    resources :users, only: [:show]
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>イーアス管理ツール</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>

    <div class="">
      <nav class="navbar navbar-default navbar-inverse">
        <div class="navbar-header">
          <a class="navbar-brand" href=<%= admin_root_path %>><%= t"layout.header.title_header" %></a>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="#"><%= t"layout.header.student" %></a></li>
          <li><a href="#"><%= t"layout.header.self_check" %></a></li>
          <li><a href="#"><%= t"layout.header.friend_hint" %></a></li>
          <!--<li><a href="#"><%#= t"layout.header.manager_user" %></a></li>-->
          <li><%= link_to t("layout.header.manager_user"), admin_users_list_path %></li>
          <%#= params[:action] == "default_admin_page" ? "" : "hidden" %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">ブログ</a>
            <ul class="dropdown-menu" style="margin-top: 3px; border-radius: 5px;">
              <li><%= link_to t("layout.header.list_blog"), admin_blogs_path %></li>
              <li><%= link_to t("layout.header.create_blog"), new_admin_blog_path %></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right" style="margin-right: 20px;">
          <% if admin_signed_in? %>
            <li>
              <%= link_to t("layout.header.logout"), admin_destroy_path, method: :delete, data: { no_turbolink: true } %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingProject</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'ckeditor/config' %>    
  </head>

 <!-- <script type="text/javascript">$(document).ready(function() {
    if ($('textarea').length > 0) {
      var data = $('textarea');
      $.each(data, function(i) {
        CKEDITOR.replace(data[i].id);
      });
    }
  });
  </script>
-->

  <body>
    <%# if user_signed_in? || admin_signed_in? %>
      <%= render 'shared/header' %>
    <%# end %>
      <%= yield %>
    <% if user_signed_in? %>
      <%= render 'shared/footer' %>
    <% end %>

    <div id="modal-flash-image" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
      <div id="welcome-text">
        <%= image_tag "first_login_image" %>
      </div>
      <div id="button-welcome">
        <a href="<%= blogs_path %>" class="btn button button-blog-list"><p class="center-text"><i class="glyphicon glyphicon-list"></i>  記事一覧を見る <i class="glyphicon glyphicon-chevron-right pull-right"></i></p></a>
        <a href="<%= author_path %>" class="btn button button-author"><p class="center-text">ナルフォード先生のプロフィールをみる<i class="glyphicon glyphicon-chevron-right pull-right"></i></p></a>
      </div>
    </div>

  </body>
  
</html>